# Purchase order statuses
PO_STATUS_DRAFT     = 'DRAFT'
PO_STATUS_SENT      = 'SENT'
PO_STATUS_PARTIAL   = 'PARTIAL'
PO_STATUS_RECEIVED  = 'RECEIVED'
PO_STATUS_CANCELLED = 'CANCELLED'
PO_STATUS_REVERSED  = 'REVERSED'

PO_STATUSES = [
    PO_STATUS_DRAFT,
    PO_STATUS_SENT,
    PO_STATUS_PARTIAL,
    PO_STATUS_RECEIVED,
    PO_STATUS_CANCELLED,
    PO_STATUS_REVERSED,
]

# Stocktake statuses
STOCKTAKE_OPEN      = 'OPEN'
STOCKTAKE_CLOSED    = 'CLOSED'
STOCKTAKE_CANCELLED = 'CANCELLED'

# User roles
ROLE_ADMIN   = 'ADMIN'
ROLE_MANAGER = 'MANAGER'
ROLE_STAFF   = 'STAFF'

# Stock movement types
MOVE_RECEIPT    = 'RECEIPT'
MOVE_SALE       = 'SALE'
MOVE_ADJUSTMENT = 'ADJUSTMENT'
MOVE_WASTAGE    = 'WASTAGE'
MOVE_REVERSAL   = 'REVERSAL'
MOVE_STOCKTAKE  = 'STOCKTAKE'

# Units
UNITS = ['EA', 'KG', 'L', 'PK', 'CTN', 'G', 'ML']

# List of movement types for stock adjustment dropdown
MOVE_TYPES = [
    'RECEIPT',
    'ADJUSTMENT_IN',
    'RETURN',
    'SALE',
    'WASTAGE',
    'ADJUSTMENT_OUT',
    'SHRINKAGE',
]
